### ISSUE TITLE
Wrong answer

### ISSUE THREAD

**Issue by SilencerChen** [kentsommer/keras-inceptionV4#13]
First of all, thank for your code, it is so helpful to me.
I am a freshman of inception model and cv. I hope to learn the model from your project. I run the project but the answer always be "sandbar" "dog" or something else and the "Certainty" is around 0.001. I change nothing and I don't konw why I could not get the right answer.
By the way ,could you explain the use of "preprocess_input"? The number all be negative after processed by it.

**Comment by kentsommer** [comment]
Hi @SilencerChen, please see this discussion: https://github.com/kentsommer/keras-inceptionV4/issues/9

**Comment by kentsommer** [comment]
@SilencerChen,

I'll be pushing changes soon to the master branch that should fix your issues.

**Comment by SilencerChen** [comment]
I download the new code 2 hours ago .
Although the url was refused so many times, I am so happy to get the right answer.
Thank you so much.
