### ISSUE TITLE
Merge this repo with Keras's applications

### ISSUE THREAD

**Issue by abrad1212** [kentsommer/keras-inceptionV4#18]
@kentsommer you should submit a PR to get this merged into Keras's Application module

**Comment by kentsommer** [comment]
@abrad1212 

I don't currently see a lot of reason for doing that. In my opinion, the Keras applications are meant to provide an introduction to different types of basic models with the least amount of friction possible to get them up and running. With InceptionV3 already there, I don't see a need to add InceptionV4 as the differences to V3 are not staggering and the hardware required to train V4 is not insignificant. So, people that want to dive deeper look for models outside the Keras applications (like this one). That is how I've always viewed it anyways. 

Perhaps if a bunch of people agree that it is worth it, I will make up a PR.

**Comment by bdwyer2** [comment]
FYI: https://github.com/fchollet/keras/pull/7847

**Comment by kentsommer** [comment]
@bdwyer2 works for me 👍

**Comment by kentsommer** [comment]
Since this is being tracked in the Keras issue mentioned above, I will close this for now.
