### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by zyavrik** [kentsommer/keras-inceptionV4#19]
Was your work based on **titu1994**'s code: https://github.com/titu1994/Inception-v4 ? It's published under MIT license. Can you include it to your repository as well?

**Comment by kentsommer** [comment]
I did not base this off of titu1994s code, I wrote this while looking at Googles tfslim implementation. If anything it should have the same license as theirs.

**Comment by zyavrik** [comment]
Thanks for providing details! Can you please just add a license file to the repository?

**Comment by kentsommer** [comment]
@zyavrik see 5dbb3533d3db1a00d39ab9b17aca55e190160cdb

**Comment by zyavrik** [comment]
So, it's Apache - not MIT?

**Comment by kentsommer** [comment]
@zyavrik Original Inception V4 is licensed under Apache, so since I wrote mine while referencing that implementation, yes it gets Apache. Apache is a very permissive license so I doubt you will run into any limitations.

**Comment by zyavrik** [comment]
Thanks!

**Comment by zyavrik** [comment]
I'm sorry, but can you also upload a license to keras-inception-resnetV2?

**Comment by zyavrik** [comment]
Is it Apache also?

**Comment by zyavrik** [comment]
The link to the **keras-inception-resnetV2** that doesn't have license file: https://github.com/kentsommer/keras-inception-resnetV2
