### ISSUE TITLE
How to train with custom dataset ?

### ISSUE THREAD

**Issue by Rahul-Venugopal** [kentsommer/keras-inceptionV4#25]
Hi ,

Is it possible to fine tune the model with pretrained weights on ImageNet for custom dataset with 3 classes ? 

Thanks 
Rahul

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github.

In short, yes it is possible. Likely you have moved on from this project but if not feel free to reopen/create a new issue and we can chat.
