### ISSUE TITLE
how can i transfer slim model to keras model

### ISSUE THREAD

**Issue by LianShuaiLong** [kentsommer/keras-inceptionV4#29]
thanks for your amazing work!
i just want to know how can i transfer origin inceptionv4 slim model to keras model
i run get_inception_weights.py firstly, and convert_weights_to_keras.py secondly（note that i have #if "dense" in layer.name:
                #       continue
）,finally i get inception-v4_weights_tf_dim_ordering_tf_kernels.h5. But it is different from inception-v4_weights_tf_dim_ordering_tf_kernels.h5 from https://github.com/kentsommer/keras-inceptionV4/releases/download/2.1/inception-v4_weights_tf_dim_ordering_tf_kernels.h5, could you help me ? i am looking forward for your reply

**Comment by kentsommer** [comment]
Closing this out after a long hiatus from Github.

Short answer is I am not sure what might have been causing the difference. Since many frameworks were upgraded since the initial release of this code it very easily could be a dependency was newer and causing some variation.
