### ISSUE TITLE
Upgrade to Keras 2

### ISSUE THREAD

**Issue by EladNoy** [kentsommer/keras-inceptionV4#6]
The current repository does not work with keras 2
Could you please create a version that is suitable for it? 

Many thanks!

**Comment by kentsommer** [comment]
Will be coming within the next couple days.

**Comment by kentsommer** [comment]
In general, I have a working Keras 2 model ready, however, due to the documented bug here https://github.com/fchollet/keras/issues/5885, theano weights are once again keeping this release tied up. Once the issues mentioned are fixed I will be pushing the 2.0 release.

**Comment by EladNoy** [comment]
Perhaps it would be possible to release a version that works for Tensorflow? Having both it and theano would be preferable, of course, but this would be better than not having V4 at all.
And once again, thank you for your time.

**Comment by kentsommer** [comment]
@EladNoy 

This Keras 2 release is now available on the Keras-2 branch. Note if you have already downloaded weights for the keras 1 release, you should clear them out of `~/.keras/models/`.
