### ISSUE TITLE
default evaluate_image.py gives wrong reasults

### ISSUE THREAD

**Issue by Huxwell** [kentsommer/keras-inceptionV4#7]
After downloading the code, and running evaluate_image.py on elephant.jpg (everything default, without changing a single line of code or the image) i get:

Loaded Model Weights!
Class is: sandbar, sand bar
Certainty is: 0.00110015

The same (sandbar) appears for different elephant images I have found.
The ordering is TF, the backend is TF as well.

**Comment by kentsommer** [comment]
@Huxwell 

I am assuming you are using Keras 2? If so please use the keras-2 branch that was recently pushed as the weight file format changed between Keras 1 and 2 so it would classify incorrectly if you were using the wrong version. 

Also remove the inception-v4 weight files from ```~/.keras/models/``` before running ```evaluate_image.py``` again to ensure the correct weights for your version are downloaded.
