### ISSUE TITLE
Training stutters on every epoch end

### ISSUE THREAD

**Issue by igrekun** [kentsommer/keras-inceptionV4#8]
Hi!

I found that after switching to Keras-2, training kind of pauses after every epoch for
a noticeable amount of time.

This doesn't happen when training network from scratch for example.

Didn't observe such behaviour when using previous version of inception_v4 with keras-1.

**Comment by igrekun** [comment]
Closing this. Validation generator is the cause, since each batch is counted as a sample, hence it takes much longer to complete validation step and it iterates over data multiple times.

**Comment by kentsommer** [comment]
:+1:
